### ISSUE TITLE
Maintain scroll position on timeline

### ISSUE THREAD

**Issue by risturiz** [NicolasConstant/sengi-electron#20] opened 2023-09-06 02:07 UTC
When the app open, timeline update and move to the top... Should be great the app keep scroll position, so we dont need to scroll back and remember last unread toot.

Thanks!

**Comment by NicolasConstant** [comment] 2024-03-15 22:27
duplicate of https://github.com/NicolasConstant/sengi/issues/469

**Closed as not planned by NicolasConstant** 2024-03-15 22:27 UTC
Labels: duplicate
