### ISSUE TITLE
Right click does nothing

### ISSUE THREAD

**Issue by stemy2** [NicolasConstant/sengi-electron#21] opened 2024-02-22 23:53 UTC
Hello,

Formerly, it was possible to do some actions with a right click, like going to a toot's webpage if you click on the toot's date of publication. But now, all we have is a context menu with "(empty)" as the only choice. Is it possible to fix a such regression ?

**Comment by NicolasConstant** [comment] 2024-02-27 22:46
duplicate of #11

**Closed as completed by NicolasConstant** 2024-02-27 22:46 UTC
Labels: duplicate
