### ISSUE TITLE
Window dimensions aren't saved

### ISSUE THREAD

**Issue by NicolasConstant** [NicolasConstant/sengi-electron#14] opened 2023-08-02 23:37 UTC
https://github.com/NicolasConstant/sengi/issues/502

**Comment by anantshri** [comment] 2024-03-11 10:29
duplicate of #3

**Closed** 2024-03-14 23:32 UTC
Labels: duplicate

**Comment by anantshri** [comment] 2024-03-15 04:47
Just checking, Is this moved into release already. coz the latest release version(1.8.0) still doesnt remember the dimension and always start in one column mode.

**Comment by NicolasConstant** [comment] 2024-03-15 22:24
No it's not, but since this issue is a duplicate (indeed), I just closed it.
